import boto3

cp = boto3.client("codepipeline")

cp.create_pipeline(
pipeline={
"name":"NodePipeline",
"roleArn":"arn:aws:iam::362223162558:role/CICDRole",
"artifactStore":{
"type":"S3",
"location":"node-source-2718"
},
"stages":[
{
"name":"Source",
"actions":[{
"name":"Source",
"actionTypeId":{
"category":"Source",
"owner":"AWS",
"provider":"S3",
"version":"1"
},
"configuration":{
"S3Bucket":"node-source-2718",
"S3ObjectKey":"app.zip",
"PollForSourceChanges":"true"
},
"outputArtifacts":[{"name":"SourceOutput"}],
"runOrder":1
}]
},
{
"name":"Build",
"actions":[{
"name":"Build",
"actionTypeId":{
"category":"Build",
"owner":"AWS",
"provider":"CodeBuild",
"version":"1"
},
"configuration":{
"ProjectName":"NodeBuild"
},
"inputArtifacts":[{"name":"SourceOutput"}],
"outputArtifacts":[{"name":"BuildOutput"}],
"runOrder":1
}]
},
{
"name":"Deploy",
"actions":[{
"name":"Deploy",
"actionTypeId":{
"category":"Deploy",
"owner":"AWS",
"provider":"S3",
"version":"1"
},
"configuration":{
"BucketName":"node-deploy-2718",
"Extract":"true"
},
"inputArtifacts":[{"name":"BuildOutput"}],
"runOrder":1
}]
}
],
"version":1
}
)

print("Pipeline Created")